import sys

molecule = "adp"
n_atoms = 39
fc = sys.argv[1]

f = open("%s_%s.itp" % (molecule, fc), 'w')	

header = "; position restraints for ADP of Generated by CHARMM-GUI FF-Converter\n\
\n\
[ position_restraints ]\n\
;  i funct       fcx        fcy        fcz\n"

f.write(header)

for i in range(1, n_atoms+1):
	f.write(str(i).ljust(8) + "1".ljust(8) + str(fc).ljust(11) + str(fc).ljust(11) + str(fc).ljust(11) + '\n')
